spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: matcher
    password: comp322

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

jwt:
  secret: asdfasdf

ImageFolder: ImageFolder